spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/synapsedb}
    username: ${DB_USERNAME:synapse}
    password: ${DB_PASSWORD:synapse123}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid,email,profile
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: read:user,user:email

app:
  cors:
    allowed-origins: http://localhost:3000,http://localhost:5173,${DEV_FRONTEND_ORIGIN:http://localhost:3000}

jwt:
  private-key: ${JWT_PRIVATE_KEY}
  public-key: ${JWT_PUBLIC_KEY}
  kid: synapse-key-2026-05
  issuer: synapse-auth
