spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/synapsedb
    username: synapse
    password: synapse123
    driver-class-name: org.postgresql.Driver

app:
  cors:
    allowed-origins: http://127.0.0.1:8088

jwt:
  private-key: ${JWT_PRIVATE_KEY}
  public-key: ${JWT_PUBLIC_KEY}
  kid: synapse-key-2026-05
  issuer: synapse-auth
